name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
      - ".ai/tmp/**"
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tooling
        run: |
          pip install pre-commit pytest ruff mypy gitleaks
      - name: Pre-commit checks
        run: pre-commit run -a
      - name: Run tests
        run: pytest -q